FROM python:3.12.2-slim

COPY requirements/requirements-ui.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ml_service/ui ml_service/ui
ENTRYPOINT ["streamlit", "run", "--server.fileWatcherType", "none", "ml_service/ui/app.py"]
