FROM python:3.12.2-slim

COPY requirements/requirements-api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ml_service/api ml_service/api
ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "ml_service.api.app:app"]
